name: signing_files
on: [push]
jobs:
  signing_files:
    runs-on: ubuntu-latest
    # 'id-token' needs write permission to retrieve the OIDC token, which is required for authentication.
    permissions:
      id-token: write
    steps:
        # This step ensures that your project is available in the workflow environment.
        - uses: actions/checkout@v4
          with:
            persist-credentials: false

        - name: Run dev container
          shell: bash
          run: |
            bash env.sh
            bash env.sh exec "bazel --output_base=target build //:main"
            bash env.sh exec "chmod -R 777 target"
            ./bazel-bin/main
        
        - uses: sigstore/gh-action-sigstore-python@v3.0.0
          with:
            inputs: ./bazel-bin/main